### ISSUE TITLE
Didn't extract all the sprites

### ISSUE THREAD

**Issue by PrincessCadenza** [magical/pokemon-gba-sprites#2]
After lots of troubleshooting with Python, I managed to get it to work, and while this might not be within the limits of the program, I wanted to see if you could help with this, since it might be a real problem as well.

The program extracted 38 different Pokemon just fine, but didn't do the rest.

In the terminal, I got this error:

Traceback (most recent call last):
  File "./rip.py", line 108, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./rip.py", line 86, in main
    pixels = read_sprite(f, front_pointers[i])
  File "./rip.py", line 48, in __call__
    x = self.func(file, pointer)
  File "sprites.pyx", line 20, in sprites.read_sprite (sprites.c:891)
    data = lzss3.decompress(f)
  File "lzss3.pyx", line 143, in lzss3.decompress (lzss3.c:1511)
    return decompress_file(obj)
  File "lzss3.pyx", line 160, in lzss3.decompress_file (lzss3.c:1758)
    return decompress_raw(f, decompressed_size)
  File "lzss3.pyx", line 59, in lzss3.decompress_raw_lzss10 (lzss3.c:1317)
    writebyte(data, &pos, size, data[pos-disp])
  File "lzss3.pyx", line 30, in lzss3.writebyte (lzss3.c:979)
    raise DecompressionError("decompressed data is larger than expected")
lzss3.DecompressionError: decompressed data is larger than expected

(I believe only the last few lines are relevant, but if the others give you context for something, I wanted to keep them in.)

Why this might not actually be a real issue is that the ROM I extracted them from was modded. Still, sprites were the only thing changed in that ROM, and the sprites that were extracted were done perfectly.

By the sound of the error, the program was expecting a different file size. Is there a way to fix this, or will I just have to do with what I have?

**Comment by PrincessCadenza** [comment]
However, I do realize that the sprites may in fact be stored in a different location than the original ROM.
